### PR TITLE
refactor: make CLI use charmil core packages

### PR DESCRIPTION
**Pull request by namit-chandwani**
Ref issue: https://github.com/aerogear/charmil/issues/234

### Description

Refactored the CLI to use core packages from Charmil (expect config, which will be done in a separate PR).

### Packages Migrated:
- [x] color
- [x] logging
- [x] localize
- [x] iostreams
- [ ] config

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [x] Other (please specify): Refactor

### Checklist

- [ ] Documentation added for the feature
- [x] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by namit-chandwani** [comment]
This PR is ready for review now.
Will be creating a separate PR for replacing the `config` package.

CC: @aerogear/charmil

**Review by ankithans — APPROVED** [review]
amazing refactoring @namit-chandwani 
This was a lot of changes. I am good to merge.

**Comment by wtrocki** [comment]
Why we doing this in host?

We typically do not care what host is using. 
It is more to make sure that plugin and hosts working together. Meaning that swapping those should probably be done on plugin (if we even need that)

My take is that for case study we should tackle possible challenges first

**Comment by ankithans** [comment]
yep, I get it. We need to figure out config - for single authentication in host and plugin.

> It is more to make sure that plugin and hosts working together. Meaning that swapping those should probably be done on plugin.

makes sense actually.

**Comment by namit-chandwani** [comment]
> This is pointless from my point of view. Why we doing it?
> 
> We typically do not care what host is using.
> It is more to make sure that plugin and hosts working together. Meaning that swapping those should probably be done on plugin.
> 
> My take is that for case study we should tackle possible challenges first

Yes, got your point.
Working on the config package now

**Comment by wtrocki** [comment]
Reason for it is to get some diff of the changes that we can apply to rhoas and apicurio..

If we start replacing other things like logs it will be all noisy and unusable.

**Comment by wtrocki** [comment]
Ignore logs and colour and other utilities that just require swap. Focus on functional elements that would not work:

- Config
- Split auth so plugin only uses own sdk
- Use commands (selected service)

**Pull request merged**
